#!/bin/bash
website=$(zenity --title="WebApper" --text="Insert the URL of the website for the WebApp" --entry)
cd $HOME
userhome=$HOME
mkdir ${userhome}/WebApps
mkdir ${userhome}/WebApps/${website}/
cd ${userhome}/WebApps/${website}/
nativefier -p linux -a x64 $website --tray
webappname=$(ls|sed s/-linux-x64//g)
webappdir=$(ls)
cd *-linux-x64
pkexec sudo chmod +x ${userhome}/WebApps/${website}/${webappdir}/*
echo -e "[Desktop Entry]\nTerminal=false\nType=Application\nCategories=Application;System;Settings;Utility;\nExec=$userhome/WebApps/$website/$webappdir/$webappname\nName=$webappname\nComment=An electron based WebApp for $webappname\nIcon=$userhome/WebApps/$website/$webappdir/resources/app/icon.png" > $userhome/.local/share/applications/$webappname.desktop
zenity --info --title="WebApper" --text="WebApp ${webappname} successfully created"
exit

